name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Sync Repository
        uses: actions/checkout@v4

      - name: Build OSL
        run: ./Build.bat
        
      - name: Upload Package
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: OSL_Windows_Package
          path: _installed/*
